# Form implementation generated from reading ui file 'system.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 395)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_ctc = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ctc.setObjectName("pushButton_ctc")
        self.verticalLayout.addWidget(self.pushButton_ctc)
        self.pushButton_trackcontrol = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_trackcontrol.setObjectName("pushButton_trackcontrol")
        self.verticalLayout.addWidget(self.pushButton_trackcontrol)
        self.pushButton_trackmodel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_trackmodel.setObjectName("pushButton_trackmodel")
        self.verticalLayout.addWidget(self.pushButton_trackmodel)
        self.pushButton_trainmodel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_trainmodel.setObjectName("pushButton_trainmodel")
        self.verticalLayout.addWidget(self.pushButton_trainmodel)
        self.pushButton_traincontrol = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_traincontrol.setObjectName("pushButton_traincontrol")
        self.verticalLayout.addWidget(self.pushButton_traincontrol)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_ctc_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ctc_test.setObjectName("pushButton_ctc_test")
        self.verticalLayout_2.addWidget(self.pushButton_ctc_test)
        self.pushButton_trackcontrol_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_trackcontrol_test.setObjectName("pushButton_trackcontrol_test")
        self.verticalLayout_2.addWidget(self.pushButton_trackcontrol_test)
        self.pushButton_trackmodel_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_trackmodel_test.setObjectName("pushButton_trackmodel_test")
        self.verticalLayout_2.addWidget(self.pushButton_trackmodel_test)
        self.pushButton_trainmodel_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_trainmodel_test.setObjectName("pushButton_trainmodel_test")
        self.verticalLayout_2.addWidget(self.pushButton_trainmodel_test)
        self.pushButton_traincontrol_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_traincontrol_test.setObjectName("pushButton_traincontrol_test")
        self.verticalLayout_2.addWidget(self.pushButton_traincontrol_test)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_ctc.setText(_translate("MainWindow", "CTC"))
        self.pushButton_trackcontrol.setText(_translate("MainWindow", "Track Control"))
        self.pushButton_trackmodel.setText(_translate("MainWindow", "Track Model"))
        self.pushButton_trainmodel.setText(_translate("MainWindow", "Train Model"))
        self.pushButton_traincontrol.setText(_translate("MainWindow", "Train Control"))
        self.pushButton_ctc_test.setText(_translate("MainWindow", "CTC Test"))
        self.pushButton_trackcontrol_test.setText(_translate("MainWindow", "Track Control Test"))
        self.pushButton_trackmodel_test.setText(_translate("MainWindow", "Track Model Test"))
        self.pushButton_trainmodel_test.setText(_translate("MainWindow", "Train Model Test"))
        self.pushButton_traincontrol_test.setText(_translate("MainWindow", "Train Control Test"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
