# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'test_form.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDial, QLabel,
    QPushButton, QSizePolicy, QWidget)

class Ui_TrainCTRLTestUI(object):
    def setupUi(self, TrainCTRLTestUI):
        if not TrainCTRLTestUI.objectName():
            TrainCTRLTestUI.setObjectName(u"TrainCTRLTestUI")
        TrainCTRLTestUI.resize(967, 250)
        self.driverSpd = QLabel(TrainCTRLTestUI)
        self.driverSpd.setObjectName(u"driverSpd")
        self.driverSpd.setGeometry(QRect(830, 330, 101, 51))
        font = QFont()
        font.setPointSize(20)
        self.driverSpd.setFont(font)
        self.activateEFault = QPushButton(TrainCTRLTestUI)
        self.activateEFault.setObjectName(u"activateEFault")
        self.activateEFault.setGeometry(QRect(60, 110, 131, 31))
        palette = QPalette()
        brush = QBrush(QColor(240, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush1 = QBrush(QColor(255, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush1)
        brush2 = QBrush(QColor(240, 240, 240, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        brush3 = QBrush(QColor(255, 255, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        self.activateEFault.setPalette(palette)
        font1 = QFont()
        font1.setPointSize(12)
        self.activateEFault.setFont(font1)
        self.activateEFault.setCheckable(False)
        self.faultLabel_2 = QLabel(TrainCTRLTestUI)
        self.faultLabel_2.setObjectName(u"faultLabel_2")
        self.faultLabel_2.setGeometry(QRect(60, 10, 161, 51))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(127, 127, 127, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(170, 170, 170, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush3)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        brush7 = QBrush(QColor(227, 227, 227, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush7)
        brush8 = QBrush(QColor(160, 160, 160, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        brush9 = QBrush(QColor(105, 105, 105, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush9)
        brush10 = QBrush(QColor(245, 245, 245, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        self.faultLabel_2.setPalette(palette1)
        font2 = QFont()
        font2.setPointSize(18)
        self.faultLabel_2.setFont(font2)
        self.activateBFault = QPushButton(TrainCTRLTestUI)
        self.activateBFault.setObjectName(u"activateBFault")
        self.activateBFault.setGeometry(QRect(60, 150, 131, 31))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Button, brush)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        self.activateBFault.setPalette(palette2)
        self.activateBFault.setFont(font1)
        self.activateBFault.setCheckable(False)
        self.activateSFault = QPushButton(TrainCTRLTestUI)
        self.activateSFault.setObjectName(u"activateSFault")
        self.activateSFault.setGeometry(QRect(60, 190, 131, 31))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Button, brush)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        self.activateSFault.setPalette(palette3)
        self.activateSFault.setFont(font1)
        self.activateSFault.setCheckable(False)
        self.iolabel = QLabel(TrainCTRLTestUI)
        self.iolabel.setObjectName(u"iolabel")
        self.iolabel.setGeometry(QRect(280, 20, 201, 51))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette4.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette4.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Midlight, brush7)
        palette4.setBrush(QPalette.Inactive, QPalette.Dark, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.Mid, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Shadow, brush9)
        palette4.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette4.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        self.iolabel.setPalette(palette4)
        self.iolabel.setFont(font2)
        self.cmdLabel = QLabel(TrainCTRLTestUI)
        self.cmdLabel.setObjectName(u"cmdLabel")
        self.cmdLabel.setGeometry(QRect(260, 70, 151, 41))
        self.curInputLabel = QLabel(TrainCTRLTestUI)
        self.curInputLabel.setObjectName(u"curInputLabel")
        self.curInputLabel.setGeometry(QRect(280, 110, 121, 41))
        self.authBox = QCheckBox(TrainCTRLTestUI)
        self.authBox.setObjectName(u"authBox")
        self.authBox.setGeometry(QRect(320, 200, 76, 20))
        self.authBox.setChecked(True)
        self.spdLimLabel = QLabel(TrainCTRLTestUI)
        self.spdLimLabel.setObjectName(u"spdLimLabel")
        self.spdLimLabel.setGeometry(QRect(300, 150, 101, 41))
        self.cmdPowOutput = QLabel(TrainCTRLTestUI)
        self.cmdPowOutput.setObjectName(u"cmdPowOutput")
        self.cmdPowOutput.setGeometry(QRect(470, 100, 411, 51))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette5.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette5.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Midlight, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.Dark, brush8)
        palette5.setBrush(QPalette.Inactive, QPalette.Mid, brush8)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Shadow, brush9)
        palette5.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        self.cmdPowOutput.setPalette(palette5)
        self.cmdPowOutput.setFont(font2)
        self.cmdSpdDial = QDial(TrainCTRLTestUI)
        self.cmdSpdDial.setObjectName(u"cmdSpdDial")
        self.cmdSpdDial.setGeometry(QRect(410, 60, 41, 51))
        self.cmdSpdDial.setMinimum(0)
        self.cmdSpdDial.setMaximum(50)
        self.cmdSpdDial.setValue(0)
        self.curSpdDial = QDial(TrainCTRLTestUI)
        self.curSpdDial.setObjectName(u"curSpdDial")
        self.curSpdDial.setGeometry(QRect(410, 110, 41, 41))
        self.curSpdDial.setMinimum(0)
        self.curSpdDial.setMaximum(40)
        self.curSpdDial.setValue(0)
        self.spdLimDial = QDial(TrainCTRLTestUI)
        self.spdLimDial.setObjectName(u"spdLimDial")
        self.spdLimDial.setGeometry(QRect(410, 150, 41, 41))
        self.spdLimDial.setMinimum(0)
        self.spdLimDial.setMaximum(40)
        self.faultReset = QPushButton(TrainCTRLTestUI)
        self.faultReset.setObjectName(u"faultReset")
        self.faultReset.setGeometry(QRect(30, 70, 191, 31))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.Button, brush)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        self.faultReset.setPalette(palette6)
        self.faultReset.setFont(font1)
        self.faultReset.setCheckable(False)

        self.retranslateUi(TrainCTRLTestUI)

        QMetaObject.connectSlotsByName(TrainCTRLTestUI)
    # setupUi

    def retranslateUi(self, TrainCTRLTestUI):
        TrainCTRLTestUI.setWindowTitle(QCoreApplication.translate("TrainCTRLTestUI", u"TrainCTRLTestUI", None))
        self.driverSpd.setText("")
        self.activateEFault.setText(QCoreApplication.translate("TrainCTRLTestUI", u"Engine Fault ", None))
        self.faultLabel_2.setText(QCoreApplication.translate("TrainCTRLTestUI", u"Fault Modes", None))
        self.activateBFault.setText(QCoreApplication.translate("TrainCTRLTestUI", u"Brake Fault", None))
        self.activateSFault.setText(QCoreApplication.translate("TrainCTRLTestUI", u"Track Signal Fault", None))
        self.iolabel.setText(QCoreApplication.translate("TrainCTRLTestUI", u"I/O Settings", None))
        self.cmdLabel.setText(QCoreApplication.translate("TrainCTRLTestUI", u"Commanded Speed:", None))
        self.curInputLabel.setText(QCoreApplication.translate("TrainCTRLTestUI", u"Current Speed: ", None))
        self.authBox.setText(QCoreApplication.translate("TrainCTRLTestUI", u"Authority", None))
        self.spdLimLabel.setText(QCoreApplication.translate("TrainCTRLTestUI", u"Speed Limit: ", None))
        self.cmdPowOutput.setText(QCoreApplication.translate("TrainCTRLTestUI", u"Commanded Power Output: ", None))
        self.faultReset.setText(QCoreApplication.translate("TrainCTRLTestUI", u"Reset Fault States", None))
    # retranslateUi

