# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_TrainModel(object):
    def setupUi(self, TrainModel):
        if not TrainModel.objectName():
            TrainModel.setObjectName(u"TrainModel")
        TrainModel.resize(800, 600)
        self.centralwidget = QWidget(TrainModel)
        self.centralwidget.setObjectName(u"centralwidget")
        self.eBrake = QPushButton(self.centralwidget)
        self.eBrake.setObjectName(u"eBrake")
        self.eBrake.setGeometry(QRect(40, 370, 201, 111))
        self.eBrake.setCheckable(True)
        self.eBrake.setChecked(False)
        self.height = QLabel(self.centralwidget)
        self.height.setObjectName(u"height")
        self.height.setGeometry(QRect(40, 30, 151, 16))
        self.width = QLabel(self.centralwidget)
        self.width.setObjectName(u"width")
        self.width.setGeometry(QRect(40, 60, 181, 16))
        self.length = QLabel(self.centralwidget)
        self.length.setObjectName(u"length")
        self.length.setGeometry(QRect(40, 90, 181, 16))
        self.passenger = QLabel(self.centralwidget)
        self.passenger.setObjectName(u"passenger")
        self.passenger.setGeometry(QRect(260, 30, 161, 16))
        self.crew = QLabel(self.centralwidget)
        self.crew.setObjectName(u"crew")
        self.crew.setGeometry(QRect(260, 60, 161, 16))
        self.mass = QLabel(self.centralwidget)
        self.mass.setObjectName(u"mass")
        self.mass.setGeometry(QRect(260, 90, 161, 16))
        self.speed = QLabel(self.centralwidget)
        self.speed.setObjectName(u"speed")
        self.speed.setGeometry(QRect(440, 30, 161, 16))
        self.accel = QLabel(self.centralwidget)
        self.accel.setObjectName(u"accel")
        self.accel.setGeometry(QRect(440, 60, 171, 16))
        self.ilight = QLabel(self.centralwidget)
        self.ilight.setObjectName(u"ilight")
        self.ilight.setGeometry(QRect(440, 90, 171, 16))
        self.rdoors = QLabel(self.centralwidget)
        self.rdoors.setObjectName(u"rdoors")
        self.rdoors.setGeometry(QRect(40, 120, 191, 16))
        self.ldoors = QLabel(self.centralwidget)
        self.ldoors.setObjectName(u"ldoors")
        self.ldoors.setGeometry(QRect(260, 120, 161, 16))
        self.temp = QLabel(self.centralwidget)
        self.temp.setObjectName(u"temp")
        self.temp.setGeometry(QRect(440, 240, 161, 16))
        self.rdoorcmd = QLabel(self.centralwidget)
        self.rdoorcmd.setObjectName(u"rdoorcmd")
        self.rdoorcmd.setGeometry(QRect(40, 150, 181, 16))
        self.ldoorcmd = QLabel(self.centralwidget)
        self.ldoorcmd.setObjectName(u"ldoorcmd")
        self.ldoorcmd.setGeometry(QRect(260, 150, 171, 16))
        self.ilightcmd = QLabel(self.centralwidget)
        self.ilightcmd.setObjectName(u"ilightcmd")
        self.ilightcmd.setGeometry(QRect(440, 150, 141, 16))
        self.ebrakecmd = QLabel(self.centralwidget)
        self.ebrakecmd.setObjectName(u"ebrakecmd")
        self.ebrakecmd.setGeometry(QRect(40, 180, 171, 16))
        self.sbrakecmd = QLabel(self.centralwidget)
        self.sbrakecmd.setObjectName(u"sbrakecmd")
        self.sbrakecmd.setGeometry(QRect(260, 180, 141, 16))
        self.powercmd = QLabel(self.centralwidget)
        self.powercmd.setObjectName(u"powercmd")
        self.powercmd.setGeometry(QRect(40, 210, 161, 16))
        self.tempcmd = QLabel(self.centralwidget)
        self.tempcmd.setObjectName(u"tempcmd")
        self.tempcmd.setGeometry(QRect(260, 240, 181, 16))
        self.speedcmd = QLabel(self.centralwidget)
        self.speedcmd.setObjectName(u"speedcmd")
        self.speedcmd.setGeometry(QRect(260, 210, 151, 16))
        self.speedlmt = QLabel(self.centralwidget)
        self.speedlmt.setObjectName(u"speedlmt")
        self.speedlmt.setGeometry(QRect(440, 210, 141, 16))
        self.grade = QLabel(self.centralwidget)
        self.grade.setObjectName(u"grade")
        self.grade.setGeometry(QRect(40, 240, 151, 16))
        self.enginefail = QPushButton(self.centralwidget)
        self.enginefail.setObjectName(u"enginefail")
        self.enginefail.setGeometry(QRect(300, 340, 201, 51))
        self.enginefail.setCheckable(True)
        self.brakefail = QPushButton(self.centralwidget)
        self.brakefail.setObjectName(u"brakefail")
        self.brakefail.setGeometry(QRect(300, 400, 201, 51))
        self.brakefail.setCheckable(True)
        self.signalfail = QPushButton(self.centralwidget)
        self.signalfail.setObjectName(u"signalfail")
        self.signalfail.setGeometry(QRect(300, 460, 201, 51))
        self.signalfail.setCheckable(True)
        self.enginefailure = QLabel(self.centralwidget)
        self.enginefailure.setObjectName(u"enginefailure")
        self.enginefailure.setGeometry(QRect(260, 270, 141, 16))
        self.brakefailure = QLabel(self.centralwidget)
        self.brakefailure.setObjectName(u"brakefailure")
        self.brakefailure.setGeometry(QRect(440, 270, 131, 16))
        self.signalfailure = QLabel(self.centralwidget)
        self.signalfailure.setObjectName(u"signalfailure")
        self.signalfailure.setGeometry(QRect(40, 270, 181, 16))
        self.elightcmd = QLabel(self.centralwidget)
        self.elightcmd.setObjectName(u"elightcmd")
        self.elightcmd.setGeometry(QRect(440, 180, 141, 16))
        self.elight = QLabel(self.centralwidget)
        self.elight.setObjectName(u"elight")
        self.elight.setGeometry(QRect(440, 120, 141, 16))
        self.station = QLabel(self.centralwidget)
        self.station.setObjectName(u"station")
        self.station.setGeometry(QRect(40, 300, 181, 16))
        self.beacon = QLabel(self.centralwidget)
        self.beacon.setObjectName(u"beacon")
        self.beacon.setGeometry(QRect(260, 300, 181, 16))
        self.auth = QLabel(self.centralwidget)
        self.auth.setObjectName(u"auth")
        self.auth.setGeometry(QRect(440, 300, 181, 16))
        self.trainSelect = QComboBox(self.centralwidget)
        self.trainSelect.setObjectName(u"trainSelect")
        self.trainSelect.setGeometry(QRect(650, 30, 141, 24))
        self.trainSelect.setEditable(False)
        TrainModel.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(TrainModel)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 31))
        TrainModel.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(TrainModel)
        self.statusbar.setObjectName(u"statusbar")
        TrainModel.setStatusBar(self.statusbar)

        self.retranslateUi(TrainModel)

        QMetaObject.connectSlotsByName(TrainModel)
    # setupUi

    def retranslateUi(self, TrainModel):
        TrainModel.setWindowTitle(QCoreApplication.translate("TrainModel", u"TrainModel", None))
        self.eBrake.setText(QCoreApplication.translate("TrainModel", u"Emergency Brake", None))
        self.height.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.width.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.length.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.passenger.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.crew.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.mass.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.speed.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.accel.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.ilight.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.rdoors.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.ldoors.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.temp.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.rdoorcmd.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.ldoorcmd.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.ilightcmd.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.ebrakecmd.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.sbrakecmd.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.powercmd.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.tempcmd.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.speedcmd.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.speedlmt.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.grade.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.enginefail.setText(QCoreApplication.translate("TrainModel", u"Train Engine Failure", None))
        self.brakefail.setText(QCoreApplication.translate("TrainModel", u"Train Brake Failure", None))
        self.signalfail.setText(QCoreApplication.translate("TrainModel", u"Signal Pickup Failure", None))
        self.enginefailure.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.brakefailure.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.signalfailure.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.elightcmd.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.elight.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.station.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.beacon.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.auth.setText(QCoreApplication.translate("TrainModel", u"TextLabel", None))
        self.label.setText("")
    # retranslateUi

