# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDial, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QSlider,
    QStatusBar, QWidget)

class Ui_TrainController(object):
    def setupUi(self, TrainController):
        if not TrainController.objectName():
            TrainController.setObjectName(u"TrainController")
        TrainController.resize(957, 633)
        self.centralwidget = QWidget(TrainController)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ilightBtn = QPushButton(self.centralwidget)
        self.ilightBtn.setObjectName(u"ilightBtn")
        self.ilightBtn.setGeometry(QRect(640, 470, 131, 51))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        palette.setBrush(QPalette.Active, QPalette.Light, brush)
        brush1 = QBrush(QColor(240, 240, 240, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        self.ilightBtn.setPalette(palette)
        font = QFont()
        font.setPointSize(14)
        self.ilightBtn.setFont(font)
        self.curTempLabel = QLabel(self.centralwidget)
        self.curTempLabel.setObjectName(u"curTempLabel")
        self.curTempLabel.setGeometry(QRect(50, 140, 161, 21))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        brush3 = QBrush(QColor(127, 127, 127, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush3)
        brush4 = QBrush(QColor(170, 170, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush2)
        brush5 = QBrush(QColor(0, 0, 0, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush6 = QBrush(QColor(227, 227, 227, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush6)
        brush7 = QBrush(QColor(160, 160, 160, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush8 = QBrush(QColor(105, 105, 105, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        brush9 = QBrush(QColor(245, 245, 245, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        self.curTempLabel.setPalette(palette1)
        font1 = QFont()
        font1.setPointSize(12)
        self.curTempLabel.setFont(font1)
        self.cmdSpd = QLabel(self.centralwidget)
        self.cmdSpd.setObjectName(u"cmdSpd")
        self.cmdSpd.setGeometry(QRect(550, 80, 331, 51))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        self.cmdSpd.setPalette(palette2)
        font2 = QFont()
        font2.setPointSize(18)
        self.cmdSpd.setFont(font2)
        self.speedSlider = QSlider(self.centralwidget)
        self.speedSlider.setObjectName(u"speedSlider")
        self.speedSlider.setGeometry(QRect(800, 270, 22, 160))
        self.speedSlider.setMaximum(40)
        self.speedSlider.setOrientation(Qt.Vertical)
        self.speedSlider.setTickPosition(QSlider.TicksBothSides)
        self.speedSlider.setTickInterval(1)
        self.intercomBtn = QPushButton(self.centralwidget)
        self.intercomBtn.setObjectName(u"intercomBtn")
        self.intercomBtn.setGeometry(QRect(70, 270, 141, 201))
        palette3 = QPalette()
        brush10 = QBrush(QColor(170, 170, 127, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush10)
        brush11 = QBrush(QColor(255, 255, 190, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush11)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        self.intercomBtn.setPalette(palette3)
        font3 = QFont()
        font3.setPointSize(20)
        self.intercomBtn.setFont(font3)
        self.intercomBtn.setCheckable(False)
        self.sBrakeBtn = QPushButton(self.centralwidget)
        self.sBrakeBtn.setObjectName(u"sBrakeBtn")
        self.sBrakeBtn.setGeometry(QRect(640, 250, 131, 191))
        palette4 = QPalette()
        brush12 = QBrush(QColor(255, 0, 0, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush12)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        brush13 = QBrush(QColor(255, 95, 89, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        brush14 = QBrush(QColor(255, 80, 80, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush14)
        self.sBrakeBtn.setPalette(palette4)
        font4 = QFont()
        font4.setPointSize(16)
        self.sBrakeBtn.setFont(font4)
        self.speedLabel = QLabel(self.centralwidget)
        self.speedLabel.setObjectName(u"speedLabel")
        self.speedLabel.setGeometry(QRect(780, 210, 151, 51))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Dark, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette5.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Midlight, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Dark, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.Mid, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette5.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush9)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        self.speedLabel.setPalette(palette5)
        self.speedLabel.setFont(font2)
        self.manModeBtn = QPushButton(self.centralwidget)
        self.manModeBtn.setObjectName(u"manModeBtn")
        self.manModeBtn.setGeometry(QRect(650, 140, 261, 61))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush12)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush14)
        self.manModeBtn.setPalette(palette6)
        self.manModeBtn.setFont(font4)
        self.eBrakeBtn = QPushButton(self.centralwidget)
        self.eBrakeBtn.setObjectName(u"eBrakeBtn")
        self.eBrakeBtn.setGeometry(QRect(300, 420, 261, 91))
        palette7 = QPalette()
        brush15 = QBrush(QColor(240, 0, 0, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush15)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush12)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        self.eBrakeBtn.setPalette(palette7)
        self.eBrakeBtn.setFont(font3)
        self.eBrakeBtn.setCheckable(False)
        self.faultLabel = QLabel(self.centralwidget)
        self.faultLabel.setObjectName(u"faultLabel")
        self.faultLabel.setGeometry(QRect(330, 160, 201, 51))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Dark, brush3)
        palette8.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette8.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Midlight, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.Dark, brush7)
        palette8.setBrush(QPalette.Inactive, QPalette.Mid, brush7)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette8.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush9)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        self.faultLabel.setPalette(palette8)
        self.faultLabel.setFont(font2)
        self.elightBtn = QPushButton(self.centralwidget)
        self.elightBtn.setObjectName(u"elightBtn")
        self.elightBtn.setGeometry(QRect(640, 530, 131, 51))
        self.elightBtn.setFont(font)
        self.curSpd = QLabel(self.centralwidget)
        self.curSpd.setObjectName(u"curSpd")
        self.curSpd.setGeometry(QRect(610, 40, 261, 51))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Dark, brush3)
        palette9.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette9.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Midlight, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.Dark, brush7)
        palette9.setBrush(QPalette.Inactive, QPalette.Mid, brush7)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette9.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush9)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette9.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        self.curSpd.setPalette(palette9)
        self.curSpd.setFont(font2)
        self.rdoorBtn = QPushButton(self.centralwidget)
        self.rdoorBtn.setObjectName(u"rdoorBtn")
        self.rdoorBtn.setGeometry(QRect(790, 530, 121, 51))
        self.rdoorBtn.setFont(font)
        self.ldoorBtn = QPushButton(self.centralwidget)
        self.ldoorBtn.setObjectName(u"ldoorBtn")
        self.ldoorBtn.setGeometry(QRect(790, 470, 121, 51))
        self.ldoorBtn.setFont(font)
        self.tempLabel = QLabel(self.centralwidget)
        self.tempLabel.setObjectName(u"tempLabel")
        self.tempLabel.setGeometry(QRect(40, 50, 231, 51))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Dark, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette10.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Midlight, brush6)
        palette10.setBrush(QPalette.Inactive, QPalette.Dark, brush7)
        palette10.setBrush(QPalette.Inactive, QPalette.Mid, brush7)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette10.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush9)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette10.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        self.tempLabel.setPalette(palette10)
        self.tempLabel.setFont(font2)
        self.tempDial = QDial(self.centralwidget)
        self.tempDial.setObjectName(u"tempDial")
        self.tempDial.setGeometry(QRect(200, 120, 50, 64))
        self.tempDial.setMinimum(55)
        self.tempDial.setMaximum(90)
        self.driverSpd = QLabel(self.centralwidget)
        self.driverSpd.setObjectName(u"driverSpd")
        self.driverSpd.setGeometry(QRect(840, 330, 101, 51))
        self.driverSpd.setFont(font3)
        self.engFailStatus = QLabel(self.centralwidget)
        self.engFailStatus.setObjectName(u"engFailStatus")
        self.engFailStatus.setGeometry(QRect(340, 210, 231, 41))
        self.trackSigStatus = QLabel(self.centralwidget)
        self.trackSigStatus.setObjectName(u"trackSigStatus")
        self.trackSigStatus.setGeometry(QRect(340, 310, 251, 31))
        self.brakeFailStatus = QLabel(self.centralwidget)
        self.brakeFailStatus.setObjectName(u"brakeFailStatus")
        self.brakeFailStatus.setGeometry(QRect(340, 260, 241, 41))
        self.powOut = QLabel(self.centralwidget)
        self.powOut.setObjectName(u"powOut")
        self.powOut.setGeometry(QRect(610, 0, 331, 51))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Dark, brush3)
        palette11.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette11.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.Midlight, brush6)
        palette11.setBrush(QPalette.Inactive, QPalette.Dark, brush7)
        palette11.setBrush(QPalette.Inactive, QPalette.Mid, brush7)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette11.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush9)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette11.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        self.powOut.setPalette(palette11)
        self.powOut.setFont(font2)
        self.trainSelect = QComboBox(self.centralwidget)
        self.trainSelect.setObjectName(u"trainSelect")
        self.trainSelect.setGeometry(QRect(30, 10, 91, 21))
        self.trainSelect.setEditable(False)
        TrainController.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(TrainController)
        self.statusbar.setObjectName(u"statusbar")
        TrainController.setStatusBar(self.statusbar)

        self.retranslateUi(TrainController)

        QMetaObject.connectSlotsByName(TrainController)
    # setupUi

    def retranslateUi(self, TrainController):
        TrainController.setWindowTitle(QCoreApplication.translate("TrainController", u"TrainController", None))
        self.ilightBtn.setText(QCoreApplication.translate("TrainController", u"Interior Lights", None))
        self.curTempLabel.setText(QCoreApplication.translate("TrainController", u"Current Temp:", None))
        self.cmdSpd.setText(QCoreApplication.translate("TrainController", u"Commanded Speed:", None))
        self.intercomBtn.setText(QCoreApplication.translate("TrainController", u"Intercom", None))
        self.sBrakeBtn.setText(QCoreApplication.translate("TrainController", u"Service Brake", None))
        self.speedLabel.setText(QCoreApplication.translate("TrainController", u"Speed Control", None))
        self.manModeBtn.setText(QCoreApplication.translate("TrainController", u"Manual Mode", None))
        self.eBrakeBtn.setText(QCoreApplication.translate("TrainController", u"Emergency Brake", None))
        self.faultLabel.setText(QCoreApplication.translate("TrainController", u"Fault Information", None))
        self.elightBtn.setText(QCoreApplication.translate("TrainController", u"Exterior Lights", None))
        self.curSpd.setText(QCoreApplication.translate("TrainController", u"Current Speed:", None))
        self.rdoorBtn.setText(QCoreApplication.translate("TrainController", u"Right Doors", None))
        self.ldoorBtn.setText(QCoreApplication.translate("TrainController", u"Left Doors", None))
        self.tempLabel.setText(QCoreApplication.translate("TrainController", u"Temperature Control", None))
        self.driverSpd.setText("")
        self.engFailStatus.setText(QCoreApplication.translate("TrainController", u"Engine Status:", None))
        self.trackSigStatus.setText(QCoreApplication.translate("TrainController", u"Track Signal Status: ", None))
        self.brakeFailStatus.setText(QCoreApplication.translate("TrainController", u"Brake Status: ", None))
        self.powOut.setText(QCoreApplication.translate("TrainController", u"Power Output:", None))
        self.trainSelect.setCurrentText("")
    # retranslateUi

